### PR TITLE
Add monthly downloads badge to README

### PR DESCRIPTION
**Pull request by Aman-Clement**
Added a monthly downloads badge by pip Trends to the README.
View more at - https://piptrends.com/widgets/fuzzysearch

### CODE REVIEW

**Comment by taleinat** [comment]
Thanks, but I'd prefer not to add this.

**Comment by Aman-Clement** [comment]
Hello @taleinat .
Thanks for the review! If there's any future interest in exploring download count features, feel free to reach out.
Thank you for your time.

**Comment by ixmatus** [comment]
@taleinat this person tried to open this exact PR against a project I'm the maintainer for as well (https://github.com/ixmatus/inflector/pull/16). This is a promotional campaign and they (or colleagues) appear to be doing it on reddit too, I think this is suspicious activity. They are creating an external dependency on a web property that (as far as I can tell) is not officially blessed by pypi. I think rejecting this PR was a good choice.

Users can get package statistics from `libraries.io` which is linked to directly by pypi itself.

**Comment by taleinat** [comment]
Thanks for the info, @ixmatus.

@Aman-Clement, for your consideration, I think it would be prudent for you to better disclose the context in which you propose such changes.

**Pull request closed without merging**
